################################################################################
#
# private-build-base/Dockerfile
#
# © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
#
################################################################################

FROM ubuntu:noble
RUN apt update \
    && apt upgrade -y \
    && apt install -y \
        autoconf \
        automake \
        build-essential \
        clang \
        curl \
        gnupg2 \
        libcurl4-openssl-dev \
        libtool \
        m4 \
        perl \
        pkg-config \
        wget \
        zsh
