################################################################################
#
# images/test/test-cache/Dockerfile
#
# © 2025 YOCKOW.
#     Licensed under MIT License.
#     See "LICENSE.txt" for more information.
#
################################################################################

FROM busybox:latest
COPY ./my-cache.txt /my-cache.txt
