name: "Build/Test/Push(if necessary)"
on:
  push:
    branches:
      - "**"
    tags:
      - "release-*"
      - "push-test-*"
  pull_request:
    branches:
      - "**"
jobs:
  build-private-build-base:
    strategy:
        matrix:
          host-os:
            - ubuntu-24.04
            - ubuntu-24.04-arm
    runs-on: ${{ matrix.host-os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/composite/build-image
        with:
          context: ./images/private-build-base
          image-basename: private-build-base
          tag-basenames: latest
          push: false