name: Test Building Docker Container Image
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - 'Dockerfile'
      - '.github/workflows/*.yml'
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/*.yml'
jobs:
  test-building-docker-container-image:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.platform }}: ${{ github.workflow }}"
    steps:
    - uses: actions/checkout@v4
    - name: Build the image
      run: docker build --platform ${{ matrix.platform }} -t test-swift-apache .
    - name: Exec "apachectl -V"
      run: docker run --rm -t test-swift-apache /opt/httpd/bin/apachectl -V
    - name: Show licenses
      run: docker run --rm -t test-swift-apache show-licenses
